In [1]:
from IPython.core.display import display, HTML
display(HTML("<style>.container { width:95% !important; }</style>"))

In [2]:
import pandas as pd
import itertools
import re
from ast import literal_eval

In [3]:
import os
os.chdir('Data_New/')

In [4]:
likes_df= pd.DataFrame()
import glob
for data in glob.glob( 'comments_likes_data_[0-9]*.csv' ):
    likes_df= likes_df.append(pd.read_csv(data), ignore_index= False)

In [5]:
likes_df.shape

(1178, 11)

In [6]:
post_df= pd.DataFrame()
import glob
for data in glob.glob( 'comments_post_data_[0-9]*.csv' ):
    post_df= post_df.append(pd.read_csv(data), ignore_index= False)

In [7]:
post_df.shape

(719, 6)

In [8]:
post_df.head()

,post_link,Profile_Link,profile_headline,likes_count,comments_count,post_content
0,https://www.linkedin.com/feed/update/urn%3Ali%...,Preksha Kaparwan,"CMO @alphaa ai, Natural Language Search for Da...",225,52 Comments,Would you rather build with people than build ...
1,https://www.linkedin.com/feed/update/urn%3Ali%...,Prudhvi Potuganti,Data Scientist | Craves to Learn | Loves to So...,664,42 Comments,Ravi Ranjan has done an incredible job by shar...
2,https://www.linkedin.com/feed/update/urn%3Ali%...,Ankit Rathi,Lead Architect - Data & AI | Author | Speaker ...,256,10 Comments,"During a recent interview, I was asked this in..."
3,https://www.linkedin.com/feed/update/urn%3Ali%...,Prudhvi Potuganti,Data Scientist | Craves to Learn | Loves to So...,141,12 Comments,The most dreadful section of feedback (for the...
4,https://www.linkedin.com/feed/update/urn%3Ali%...,Ritesh Bhagwat,Data Scientist | Applied Mathematics | Spiritu...,132,4 Comments,If I write a book on how to waste 40 years of ...

In [9]:
post_df.shape

(719, 6)

In [10]:
date_df= pd.read_csv('../../data_dump/Comments.csv')

In [11]:
date_df

,Date,Link,Message
0,2019-11-03 14:51:55,https://www.linkedin.com/feed/update/urn%3Ali%...,Lovely question. My situation is peculiar. I b...
1,2019-11-03 11:33:52,https://www.linkedin.com/feed/update/urn%3Ali%...,Very well said !
2,2019-11-03 06:07:48,https://www.linkedin.com/feed/update/urn%3Ali%...,Let me see.
3,2019-11-03 02:47:19,https://www.linkedin.com/feed/update/urn%3Ali%...,Ankit Rathi I can never match yours or Srivat...
4,I still remember Sachin Tripathi podcast with ...,NaN,NaN
...,...,...,...
1120,2013-11-21 00:38:48,https://www.linkedin.com/feed/update/urn%3Ali%...,congrats bhai !!
1121,2013-11-01 10:46:02,https://www.linkedin.com/feed/update/urn%3Ali%...,Thank you guys. I need to keep this up. That's...
1122,2013-11-01 10:45:39,https://www.linkedin.com/feed/update/urn%3Ali%...,Thank you guys. I need to keep this up. That's...
1123,2013-06-04 05:01:55,https://www.linkedin.com/feed/update/urn%3Ali%...,congratulations !!
1124,2013-06-04 05:01:30,https://www.linkedin.com/feed/update/urn%3Ali%...,congratulations !!

In [12]:
i=0
while(i < date_df.shape[0]):
    if pd.isnull(date_df.Link[i]):
        date_df.Message[i-1]= str(date_df.Message[i-1]) + str(date_df.Date[i])
        date_df.Message[i-1]= date_df.Message[i-1].replace('nan', '')
        date_df.drop(date_df.index[i], inplace= True)
        date_df.reset_index(drop= True, inplace= True)
        i = i - 1
    i = i + 1

In [13]:
date_df.head()

,Date,Link,Message
0,2019-11-03 14:51:55,https://www.linkedin.com/feed/update/urn%3Ali%...,Lovely question. My situation is peculiar. I b...
1,2019-11-03 11:33:52,https://www.linkedin.com/feed/update/urn%3Ali%...,Very well said !
2,2019-11-03 06:07:48,https://www.linkedin.com/feed/update/urn%3Ali%...,Let me see.
3,2019-11-03 02:47:19,https://www.linkedin.com/feed/update/urn%3Ali%...,Ankit Rathi I can never match yours or Srivat...
4,2019-11-02 11:12:12,https://www.linkedin.com/feed/update/urn%3Ali%...,Wow ! This is a privelege. When I started Link...

In [14]:
date_df.shape

(938, 3)

In [15]:
date_df.drop_duplicates(subset= 'Link', inplace= True)

In [16]:
date_df.shape

(601, 3)

In [17]:
post_df= pd.merge(post_df, date_df, how= 'left', left_on= 'post_link', right_on= 'Link')

In [18]:
post_df.shape

(719, 9)

In [21]:
post_df

,post_link,Profile_Link,profile_headline,likes_count,comments_count,post_content,Date,Link,Message
0,https://www.linkedin.com/feed/update/urn%3Ali%...,Preksha Kaparwan,"CMO @alphaa ai, Natural Language Search for Da...",225,52 Comments,Would you rather build with people than build ...,2019-11-03 14:51:55,https://www.linkedin.com/feed/update/urn%3Ali%...,Lovely question. My situation is peculiar. I b...
1,https://www.linkedin.com/feed/update/urn%3Ali%...,Prudhvi Potuganti,Data Scientist | Craves to Learn | Loves to So...,664,42 Comments,Ravi Ranjan has done an incredible job by shar...,2019-11-03 11:33:52,https://www.linkedin.com/feed/update/urn%3Ali%...,Very well said !
2,https://www.linkedin.com/feed/update/urn%3Ali%...,Ankit Rathi,Lead Architect - Data & AI | Author | Speaker ...,256,10 Comments,"During a recent interview, I was asked this in...",2019-11-03 02:47:19,https://www.linkedin.com/feed/update/urn%3Ali%...,Ankit Rathi I can never match yours or Srivat...
3,https://www.linkedin.com/feed/update/urn%3Ali%...,Prudhvi Potuganti,Data Scientist | Craves to Learn | Loves to So...,141,12 Comments,The most dreadful section of feedback (for the...,2019-11-02 06:57:59,https://www.linkedin.com/feed/update/urn%3Ali%...,Subbaraju I Thank you
4,https://www.linkedin.com/feed/update/urn%3Ali%...,Ritesh Bhagwat,Data Scientist | Applied Mathematics | Spiritu...,132,4 Comments,If I write a book on how to waste 40 years of ...,2019-11-02 06:55:55,https://www.linkedin.com/feed/update/urn%3Ali%...,"With your sarcasm, you are promoting failure a..."
...,...,...,...,...,...,...,...,...,...
714,https://www.linkedin.com/feed/update/urn%3Ali%...,Prudhvi Potuganti,Data Scientist | Craves to Learn | Loves to So...,328,36 Comments,Not a single ad placed. Not a single follow up...,2019-09-22 02:46:09,https://www.linkedin.com/feed/update/urn%3Ali%...,Appreciate this Mayur
715,https://www.linkedin.com/feed/update/urn%3Ali%...,Amit Choudhary,Educator l Building Data Pipelines for solving...,16,1 Comment,You know you are doing great when people are t...,2019-09-21 16:53:11,https://www.linkedin.com/feed/update/urn%3Ali%...,Amit Choudhary wow. This is awesome. And suppo...
716,https://www.linkedin.com/feed/update/urn%3Ali%...,Ritesh Bhagwat,Data Scientist | Applied Mathematics | Spiritu...,136,6 Comments,Again hashtag#sarcasm ahead.. Life was going o...,2019-09-20 00:02:22,https://www.linkedin.com/feed/update/urn%3Ali%...,So the p( ritesh post/ rsarcasm) has increased...
717,https://www.linkedin.com/feed/update/urn%3Ali%...,Shubhi Saxena,Conversational AI | Finance | Tech,100,5 Comments,I will be consolidating all my experience of b...,2019-09-19 23:57:56,https://www.linkedin.com/feed/update/urn%3Ali%...,Awesome !
718,https://www.linkedin.com/feed/update/urn%3Ali%...,Preksha Kaparwan,"CMO @alphaa ai, Natural Language Search for Da...",575,68 Comments,Being an hashtag#enterprenuer doesn't mean you...,2019-09-19 16:23:05,https://www.linkedin.com/feed/update/urn%3Ali%...,I see many people are buying hype in our field...

In [23]:
dates_df= pd.merge(likes_df, post_df, how= 'left', left_on= 'comment_post_link', right_on= 'Link')

In [25]:
dates_df.to_excel('../dates.xlsx', index= False)

In [28]:
pd.set_option('display.max_rows', 1200)
dates_df[['comment_likes_counts', 'Date']]

     comment_likes_counts                 Date
0                       1  2019-11-03 14:51:55
1                       0  2019-11-03 11:33:52
2                       1  2019-11-03 11:33:52
3                       1  2019-11-03 11:33:52
4                      24  2019-11-03 02:47:19
5                       2  2019-11-03 02:47:19
6                       1  2019-11-02 06:57:59
7                       4  2019-11-02 06:55:55
8                      10  2019-11-02 01:49:19
9                       0  2019-11-02 01:49:19
10                     10  2019-11-01 14:45:47
11                      0  2019-11-01 14:45:47
12                      5  2019-11-01 05:52:42
13                      4  2019-11-01 05:15:17
14                      0  2019-11-01 01:57:36
15                      0  2019-11-01 01:57:36
16                      0  2019-09-18 17:38:53
17                      0  2019-09-18 17:38:53
18                      0  2019-09-18 17:38:53
19                      1  2019-09-18 17:38:53
20                      0  2019-09-18 17:38:53
21                      0  2019-09-18 17:38:53
22                      1  2019-09-18 17:38:53
23                      1  2019-09-18 01:16:43
24                      5  2019-09-18 01:16:43
25                      2  2019-09-17 17:57:18
26                      1  2019-09-17 17:42:14
27                     81  2019-09-17 17:40:35
28                      4  2019-09-17 17:40:35
29                      0  2019-09-17 17:40:35
30                      1  2019-09-17 17:40:35
31                      7  2019-09-17 10:31:59
32                     22  2019-09-17 06:51:12
33                      2  2019-09-17 06:51:12
34                      1  2019-09-17 06:51:12
35                      0  2019-09-17 06:51:12
36                     16  2019-09-17 04:53:33
37                      2  2019-09-17 04:40:59
38                      0  2019-09-16 11:30:14
39                      0  2019-09-16 11:30:14
40                      0  2019-09-16 11:30:14
41                      0  2019-09-16 11:30:14
42                     25  2019-09-15 12:48:14
43                     25  2019-09-14 07:38:01
44                      0  2019-09-14 07:38:01
45                      4  2019-09-13 17:10:22
46                      5  2019-09-13 10:16:41
47                      0  2019-09-13 10:16:41
48                     85  2019-09-12 04:45:31
49                      1  2019-09-12 04:45:31
50                      0  2019-09-12 04:45:31
51                      2  2019-09-12 04:45:31
52                      2  2019-09-11 09:08:03
53                      1  2019-09-11 09:08:03
54                      4  2019-09-11 05:00:16
55                      0  2019-09-09 09:30:55
56                      0  2019-09-09 09:30:55
57                      0  2019-09-09 09:30:55
58                      0  2019-09-09 09:30:55
59                      0  2019-09-09 09:30:55
60                      8  2019-09-09 04:35:12
61                      3  2019-09-08 17:16:23
62                      0  2019-09-08 04:50:06
63                      3  2019-09-08 04:50:06
64                      0  2019-09-08 04:50:06
65                      0  2019-09-08 04:50:06
66                      1  2019-09-06 13:47:11
67                     21  2019-09-06 08:33:53
68                      0  2019-09-06 07:20:25
69                      5  2019-09-06 06:27:04
70                      2  2019-09-05 07:00:07
71                      0  2019-09-05 07:00:07
72                      2  2019-09-05 03:37:08
73                      3  2019-09-05 03:29:28
74                      5  2019-09-04 15:06:35
75                     21  2019-09-04 14:37:46
76                      2  2019-09-04 14:37:46
77                      0  2019-09-04 14:37:46
78                     15  2019-09-04 08:20:20
79                     14  2019-09-04 07:20:24
80                      3  2019-09-04 02:36:06
81                      1  2019-09-03 14:41:31
82                      0  2019-09-03 00:33:50
83                      0  2019-09-03 00:33:50
84                      0  2019-09-02 23:51:08
85                      1  2019-09-02 17:28:39
86                      7  2019-09-02 12:11:52
87                      3  2019-09-01 12:00:24
88                      7  2019-09-01 05:28:29
89                      1  2019-09-01 05:28:29
90                      0  2019-08-31 09:05:10
91                      3  2019-08-31 03:53:04
92                     25  2019-08-31 01:15:56
93                      0  2019-08-31 01:15:56
94                      1  2019-08-30 01:51:00
95                      4  2019-08-29 12:12:47
96                      7  2019-08-29 04:05:05
97                      1  2019-08-29 04:03:28
98                      3  2019-08-29 04:03:28
99                      9  2019-08-29 04:03:28
100                     1  2019-08-29 04:03:28
101                     2  2019-08-29 04:03:28
102                     1  2019-08-29 04:03:28
103                     0  2019-08-29 04:03:28
104                     1  2019-08-29 04:03:28
105                     0  2019-08-29 04:03:28
106                     1  2019-08-29 04:03:28
107                     0  2019-08-29 04:03:28
108                     2  2019-08-26 15:12:09
109                     4  2019-08-26 10:25:35
110                     0  2019-08-26 09:05:12
111                     0  2019-08-26 09:05:12
112                     1  2019-08-26 09:05:12
113                     0  2019-08-26 09:05:12
114                     1  2019-08-26 09:05:12
115                    23  2019-08-26 08:49:19
116                     1  2019-08-26 01:19:32
117                     2  2019-08-25 10:17:39
118                     1  2019-08-25 01:32:50
119                     1  2019-08-25 01:32:50
120                    25  2019-08-24 05:29:08
121                     3  2019-08-23 08:21:35
122                    12  2019-08-23 05:13:21
123                     1  2019-08-23 05:13:21
124                     5  2019-08-23 00:52:27
125                    10  2019-08-22 04:16:17
126                     1  2019-08-22 04:16:17
127                     3  2019-08-21 16:19:46
128                     2  2019-08-21 15:47:23
129                    26  2019-08-21 12:23:03
130                    21  2019-08-19 04:51:26
131                    25  2019-08-17 15:49:19
132                    55  2019-08-17 10:23:15
133                     5  2019-08-17 09:07:25
134                    12  2019-08-16 09:58:31
135                     2  2019-08-15 13:39:41
136                     1  2019-08-13 12:31:01
137                    50  2019-08-12 12:34:00
138                     0  2019-08-12 12:34:00
139                     1  2019-08-12 12:34:00
140                     0  2019-08-12 08:04:07
141                     4  2019-08-07 11:00:16
142                     0  2019-08-07 11:00:16
143                    13  2019-08-06 04:50:56
144                    13  2019-08-06 04:50:56
145                     0  2019-08-05 01:56:49
146                    34  2019-08-04 04:22:09
147                     1  2019-08-04 04:22:09
148                     6  2019-08-03 19:46:04
149                     0  2019-08-03 19:46:04
150                    13  2019-08-03 07:16:30
151                     1  2019-08-02 17:18:09
152                    14  2019-08-02 09:00:48
153                    37  2019-08-02 07:51:54
154                     1  2019-08-02 07:51:54
155                     7  2019-07-30 03:47:57
156                     0  2019-07-29 09:51:30
157                     0  2019-07-29 09:51:30
158                     0  2019-07-29 09:51:30
159                     0  2019-07-29 09:51:30
160                     0  2019-07-29 09:51:30
161                     1  2019-07-29 05:05:13
162                     6  2019-07-28 13:35:02
163                    35  2019-07-28 07:45:31
164                     2  2019-07-28 07:45:31
165                     3  2019-07-27 09:50:17
166                     6  2019-07-26 07:10:58
167                     2  2019-07-25 06:50:26
168                     5  2019-07-25 06:50:26
169                     6  2019-07-25 05:52:07
170                     1  2019-07-25 05:45:09
171                     0  2019-07-25 05:45:09
172                     1  2019-07-25 05:45:09
173                     1  2019-07-25 05:45:09
174                     1  2019-07-25 05:45:09
175                     2  2019-07-25 02:18:58
176                     2  2019-07-24 08:41:58
177                     0  2019-07-23 12:25:43
178                     0  2019-07-23 02:57:41
179                    11  2019-07-23 02:57:41
180                     1  2019-07-19 00:33:23
181                     2  2019-07-18 03:29:31
182                     4  2019-07-16 09:35:13
183                     1  2019-07-16 09:35:13
184                     1  2019-10-31 16:54:08
185                    17  2019-10-31 16:51:35
186                     0  2019-10-30 16:08:20
187                     2  2019-10-30 16:08:20
188                     0  2019-10-30 16:08:20
189                     1  2019-10-30 16:08:20
190                     2  2019-10-30 16:08:20
191                     0  2019-10-30 16:08:20
192                    40  2019-10-29 16:57:15
193                     0  2019-10-29 12:10:23
194                     1  2019-10-29 05:51:44
195                    38  2019-10-29 05:51:44
196                    10  2019-10-29 05:51:44
197                     5  2019-10-29 05:36:59
198                     3  2019-10-28 18:49:40
199                     0  2019-10-28 12:18:35
200                     0  2019-10-28 12:18:35
201                     5  2019-10-28 07:14:54
202                    11  2019-07-16 05:13:52
203                     2  2019-07-16 05:13:52
204                     1  2019-07-15 15:59:12
205                     0  2019-07-15 15:59:12
206                     0  2019-07-15 15:59:12
207                     1  2019-07-15 12:29:12
208                     3  2019-07-15 07:54:18
209                    18  2019-07-14 16:14:23
210                     0  2019-07-12 08:40:10
211                     2  2019-07-12 07:06:12
212                     1  2019-07-12 07:06:12
213                     0  2019-07-12 07:06:12
214                     0  2019-07-11 13:13:54
215                     0  2019-07-11 13:13:54
216                     0  2019-07-11 13:13:54
217                     0  2019-07-11 13:13:54
218                     8  2019-07-11 04:23:53
219                     2  2019-07-10 13:14:21
220                    25  2019-07-10 11:12:46
221                     7  2019-07-10 00:35:59
222                     0  2019-07-10 00:35:59
223                     1  2019-07-09 16:56:01
224                     6  2019-07-08 13:24:53
225                     0  2019-07-08 13:09:21
226                     0  2019-07-08 13:09:21
227                     0  2019-07-08 13:09:21
228                    13  2019-07-08 13:08:27
229                     4  2019-07-08 07:33:41
230                     1  2019-07-08 06:07:02
231                     0  2019-07-07 11:27:30
232                    12  2019-07-06 11:06:52
233                    16  2019-07-06 02:56:34
234                    13  2019-07-05 14:14:28
235                     2  2019-07-05 12:29:12
236                     2  2019-07-04 03:49:16
237                     0  2019-07-02 23:34:53
238                     2  2019-07-02 23:31:43
239                     4  2019-07-02 17:39:10
240                     2  2019-07-02 10:41:34
241                     1  2019-07-01 10:18:12
242                     1  2019-07-01 04:14:55
243                    12  2019-06-30 15:58:27
244                    70  2019-06-30 11:30:38
245                     1  2019-06-30 08:36:28
246                     1  2019-06-30 00:36:18
247                     1  2019-06-29 15:20:30
248                    12  2019-06-28 12:53:59
249                     1  2019-06-28 08:10:19
250                     0  2019-06-28 08:10:19
251                    25  2019-06-28 08:10:19
252                     1  2019-06-28 06:03:14
253                     0  2019-06-28 06:03:14
254                     0  2019-06-28 06:03:14
255                     4  2019-06-27 16:10:26
256                     1  2019-06-27 09:24:47
257                     6  2019-06-26 17:30:02
258                     1  2019-06-26 17:30:02
259                     5  2019-06-26 06:31:46
260                     0  2019-06-26 05:32:56
261                     0  2019-06-26 05:32:56
262                     1  2019-06-26 05:32:56
263                     0  2019-06-26 05:32:56
264                     0  2019-06-26 05:32:56
265                     0  2019-06-26 05:32:56
266                    12  2019-06-26 00:26:36
267                     1  2019-06-25 16:00:24
268                    33  2019-06-24 03:12:17
269                     2  2019-06-24 03:12:17
270                     2  2019-06-21 15:08:41
271                     1  2019-06-21 11:40:56
272                     0  2019-06-21 11:40:56
273                     1  2019-06-21 10:03:10
274                     3  2019-06-21 09:42:15
275                     0  2019-06-21 07:34:39
276                     1  2019-06-21 07:34:39
277                     6  2019-06-21 07:28:20
278                     1  2019-06-21 07:28:20
279                     4  2019-06-21 06:33:47
280                   101  2019-06-20 03:56:43
281                     2  2019-06-19 16:20:13
282                     0  2019-06-19 15:32:32
283                     1  2019-06-19 15:32:32
284                     1  2019-06-19 15:32:32
285                    12  2019-06-19 03:14:25
286                     2  2019-06-18 06:05:46
287                     0  2019-06-16 15:08:08
288                     5  2019-06-16 13:00:25
289                     5  2019-06-16 02:01:54
290                     0  2019-06-16 02:01:54
291                     0  2019-06-15 11:20:40
292                     1  2019-06-15 11:20:40
293                     0  2019-06-15 11:20:40
294                     0  2019-06-15 11:20:40
295                     0  2019-06-15 11:20:40
296                     0  2019-06-15 11:20:40
297                     0  2019-06-15 11:20:40
298                     0  2019-06-15 11:20:40
299                     0  2019-06-15 11:20:40
300                     0  2019-06-15 11:20:40
301                     0  2019-06-15 11:20:40
302                     0  2019-06-15 11:20:40
303                     0  2019-06-15 11:20:40
304                     0  2019-06-15 11:20:40
305                     0  2019-06-15 11:20:40
306                     0  2019-06-15 11:20:40
307                     0  2019-06-15 11:20:40
308                     0  2019-06-15 11:20:40
309                     0  2019-06-15 11:20:40
310                     0  2019-06-15 11:20:40
311                     0  2019-06-15 11:20:40
312                     0  2019-06-15 11:20:40
313                     0  2019-06-15 11:20:40
314                     0  2019-06-15 11:20:40
315                     0  2019-06-15 11:20:40
316                     0  2019-06-15 11:20:40
317                     0  2019-06-15 11:20:40
318                     0  2019-06-15 11:20:40
319                     0  2019-06-15 11:20:40
320                     0  2019-06-15 11:20:40
321                     0  2019-06-15 11:20:40
322                     0  2019-06-15 11:20:40
323                     4  2019-06-12 12:09:31
324                     2  2019-06-11 12:57:32
325                     1  2019-06-05 16:47:46
326                     2  2019-06-05 05:21:07
327                     1  2019-06-05 05:21:07
328                     7  2019-06-04 13:32:44
329                     4  2019-06-03 16:44:01
330                     3  2019-06-03 12:31:33
331                     7  2019-06-03 03:09:03
332                    14  2019-06-03 03:03:52
333                    10  2019-06-03 03:02:23
334                     1  2019-06-03 03:02:23
335                     1  2019-06-02 12:06:35
336                     1  2019-06-02 03:59:14
337                    15  2019-06-02 02:26:21
338                     2  2019-06-01 11:55:44
339                     1  2019-05-31 14:58:18
340                     2  2019-05-31 09:04:12
341                     1  2019-05-31 03:06:53
342                     6  2019-05-30 14:43:03
343                     2  2019-05-30 13:04:24
344                     2  2019-05-30 09:12:47
345                     2  2019-05-29 14:51:52
346                    81  2019-05-29 14:45:56
347                     3  2019-10-28 06:54:19
348                     8  2019-10-27 16:16:26
349                     1  2019-10-27 14:18:41
350                     0  2019-10-27 14:18:41
351                     0  2019-10-27 14:18:41
352                     0  2019-10-27 14:18:41
353                     4  2019-10-27 05:22:03
354                     2  2019-10-27 05:22:03
355                     2  2019-10-27 00:46:29
356                     0  2019-10-27 00:46:29
357                    15  2019-10-26 12:15:30
358                     2  2019-10-26 12:15:30
359                     0  2019-10-26 12:15:30
360                    56  2019-10-26 03:39:47
361                    14  2019-10-24 14:48:37
362                     0  2019-10-24 11:04:52
363                     1  2019-10-24 03:36:59
364                     0  2019-10-24 03:36:59
365                     0  2019-10-24 03:36:59
366                     0  2019-05-28 14:51:13
367                     6  2019-05-28 04:08:17
368                     8  2019-05-27 16:29:55
369                     1  2019-05-27 16:18:28
370                     3  2019-05-27 13:00:33
371                     6  2019-05-27 08:14:51
372                     0  2019-05-27 08:14:51
373                     0  2019-05-26 09:13:48
374                    13  2019-05-25 15:30:51
375                     2  2019-05-25 15:30:51
376                     2  2019-05-25 15:30:51
377                     2  2019-05-25 15:16:07
378                     7  2019-05-25 10:42:03
379                     9  2019-05-24 08:46:15
380                     3  2019-05-23 18:38:36
381                     0  2019-05-23 13:18:17
382                     4  2019-05-23 13:15:16
383                     1  2019-05-23 13:14:30
384                     0  2019-05-23 13:14:30
385                     0  2019-05-22 15:57:33
386                     1  2019-05-22 15:57:33
387                     1  2019-05-22 10:24:05
388                     4  2019-05-21 10:13:13
389                     0  2019-05-21 09:01:54
390                     7  2019-05-20 16:21:18
391                     4  2019-05-19 13:42:43
392                    17  2019-05-19 10:26:08
393                    34  2019-05-19 10:21:51
394                    13  2019-05-19 02:14:29
395                     4  2019-05-18 09:24:41
396                     0  2019-05-18 02:07:23
397                    30  2019-05-17 16:33:52
398                    12  2019-05-15 16:37:04
399                     0  2019-05-14 16:18:20
400                     0  2019-05-13 10:25:27
401                     0  2019-05-13 10:25:27
402                     9  2019-05-12 15:41:03
403                     0  2019-05-10 17:24:19
404                     1  2019-05-10 17:24:19
405                     5  2019-05-10 03:40:14
406                     0  2019-05-10 03:40:14
407                     0  2019-05-09 13:08:14
408                    17  2019-05-09 05:00:01
409                     0  2019-05-08 15:12:51
410                     5  2019-05-08 11:55:34
411                     1  2019-05-08 07:18:15
412                     0  2019-05-08 03:48:20
413                     2  2019-05-07 08:06:09
414                     3  2019-05-07 08:04:33
415                     2  2019-05-07 07:43:55
416                     0  2019-05-07 07:43:55
417                    26  2019-05-05 14:19:40
418                     5  2019-05-05 02:43:22
419                     3  2019-05-05 02:15:08
420                     2  2019-05-05 02:11:31
421                     2  2019-05-05 02:11:31
422                     0  2019-05-05 02:11:31
423                     0  2019-05-05 02:11:31

In [11]:
likes_df.like_names= likes_df.like_names.fillna("['NaN']").apply(literal_eval)

In [12]:
like_names = [item for sublist in likes_df.like_names.tolist() for item in sublist]

In [13]:
likes_counts= pd.DataFrame({'names': like_names})
likes_counts= likes_counts[likes_counts.names!= 'NaN']

In [14]:
likes_counts.names= likes_counts.names.apply(lambda x: x.split('\n')[1].strip())

In [15]:
likes_counts.to_excel('../likes.xlsx', index= False)

In [16]:
likes_df.comments_replies_names= likes_df.comments_replies_names.fillna("['NaN']").apply(literal_eval)

In [17]:
replies_names = [item for sublist in likes_df.comments_replies_names.tolist() for item in sublist]

In [18]:
replies_count= pd.DataFrame({'names': replies_names})
replies_count= replies_count[replies_count.names!= 'NA']

In [19]:
replies_count.to_excel('../replies.xlsx', index= False)