In [1]:
from IPython.core.display import display, HTML
display(HTML("<style>.container { width:97% !important; }</style>"))

In [2]:
import pandas as pd
import itertools
import re
from ast import literal_eval

In [7]:
df= pd.read_csv('../new_data_dump/Reactions.csv')

In [8]:
df.head()

,Date,Type,Link
0,2020-02-15 11:45:01,LIKE,https://www.linkedin.com/feed/update/urn%3Ali%...
1,2020-02-15 09:50:34,LIKE,https://www.linkedin.com/feed/update/urn%3Ali%...
2,2020-02-15 09:50:23,LIKE,https://www.linkedin.com/feed/update/urn%3Ali%...
3,2020-02-15 08:15:33,LIKE,https://www.linkedin.com/feed/update/urn%3Ali%...
4,2020-02-15 08:15:12,LIKE,https://www.linkedin.com/feed/update/urn%3Ali%...

In [11]:
df= df.drop_duplicates(subset= 'Link')
df.reset_index(drop= True ,inplace= True)

In [12]:
df.shape

(1974, 3)

In [13]:
df['corp']= df.Link.apply(lambda x: 'Comment' if 'comment' in str(x) else 'post')

In [14]:
df.corp.value_counts()

Comment    1409
post        565
Name: corp, dtype: int64

In [15]:
for link in df.Link[:10]:
    print(link)
    print("-----")

https://www.linkedin.com/feed/update/urn%3Ali%3Aactivity%3A6633959670044254209?commentUrn=urn%3Ali%3Acomment%3A%28activity%3A6633959670044254209%2C6634388803412951040%29
-----
https://www.linkedin.com/feed/update/urn%3Ali%3Aactivity%3A6633959670044254209?commentUrn=urn%3Ali%3Acomment%3A%28activity%3A6633959670044254209%2C6634361265139617792%29
-----
https://www.linkedin.com/feed/update/urn%3Ali%3Aactivity%3A6633959670044254209?commentUrn=urn%3Ali%3Acomment%3A%28activity%3A6633959670044254209%2C6634369866184921088%29
-----
https://www.linkedin.com/feed/update/urn%3Ali%3Aactivity%3A6633959670044254209?commentUrn=urn%3Ali%3Acomment%3A%28activity%3A6633959670044254209%2C6634332488820985856%29
-----
https://www.linkedin.com/feed/update/urn%3Ali%3Aactivity%3A6633959670044254209?commentUrn=urn%3Ali%3Acomment%3A%28activity%3A6633959670044254209%2C6634343176041783297%29
-----
https://www.linkedin.com/feed/update/urn%3Ali%3Aactivity%3A6633959670044254209?commentUrn=urn%3Ali%3Acomment%3A%28activity%3A6633959670044254209%2C6633986450654355456%29
-----
https://www.linkedin.com/feed/update/urn%3Ali%3Aactivity%3A6633959670044254209?commentUrn=urn%3Ali%3Acomment%3A%28activity%3A6633959670044254209%2C6634094684492886017%29
-----
https://www.linkedin.com/feed/update/urn%3Ali%3Aactivity%3A6633959670044254209?commentUrn=urn%3Ali%3Acomment%3A%28activity%3A6633959670044254209%2C6634084464022654976%29
-----
https://www.linkedin.com/feed/update/urn%3Ali%3Aactivity%3A6633959670044254209?commentUrn=urn%3Ali%3Acomment%3A%28activity%3A6633959670044254209%2C6634192097434005504%29
-----
https://www.linkedin.com/feed/update/urn%3Ali%3Aactivity%3A6633959670044254209?commentUrn=urn%3Ali%3Acomment%3A%28activity%3A6633959670044254209%2C6634000830926295041%29
-----

In [29]:
comment= df.Link[0]

In [30]:
import re

In [31]:
comment= [com[2:] for com in re.findall('[A-Za-z0-9]{2}[0-9]{19}', comment)]

In [32]:
comment

['6633959670044254209', '6633959670044254209', '6634388803412951040']

In [33]:
res = [] 
for i in comment: 
    if i not in res: 
        res.append(i)

In [34]:
comment= res

In [35]:
comment

['6633959670044254209', '6634388803412951040']

In [36]:
data_id = f'//article[@data-id="urn:li:comment:(activity:{comment[0]},{comment[1]})"]'

In [37]:
data_id

'//article[@data-id="urn:li:comment:(activity:6633959670044254209,6634388803412951040)"]'

In [4]:
i=0
while(i < df.shape[0]):
            if pd.isnull(df.Link[i]):
                df.Message[i-1]= str(df.Message[i-1]) + str(df.Date[i])
                df.Message[i-1]= df.Message[i-1].replace('nan', '')
                df.drop(df.index[i], inplace= True)
                df.reset_index(drop= True, inplace= True)
                i = i - 1
            i = i + 1

In [5]:
new_df= pd.read_csv('../new_data_dump/Comments.csv')

In [6]:
i=0
while(i < new_df.shape[0]):
            if pd.isnull(new_df.Link[i]):
                new_df.Message[i-1]= str(new_df.Message[i-1]) + str(new_df.Date[i])
                new_df.Message[i-1]= new_df.Message[i-1].replace('nan', '')
                new_df.drop(new_df.index[i], inplace= True)
                new_df.reset_index(drop= True, inplace= True)
                i = i - 1
            i = i + 1

In [7]:
new_comments_df = new_df[~new_df.Link.isin(df.Link)]

In [8]:
new_comments_df.to_csv('Comments_new.csv', index= False)

In [9]:
new_comments_df.Link

0      https://www.linkedin.com/feed/update/urn%3Ali%...
1      https://www.linkedin.com/feed/update/urn%3Ali%...
2      https://www.linkedin.com/feed/update/urn%3Ali%...
3      https://www.linkedin.com/feed/update/urn%3Ali%...
4      https://www.linkedin.com/feed/update/urn%3Ali%...
                             ...
309    https://www.linkedin.com/feed/update/urn%3Ali%...
310    https://www.linkedin.com/feed/update/urn%3Ali%...
311    https://www.linkedin.com/feed/update/urn%3Ali%...
312    https://www.linkedin.com/feed/update/urn%3Ali%...
314    https://www.linkedin.com/feed/update/urn%3Ali%...
Name: Link, Length: 312, dtype: object

In [ ]:
new_df= pd.read_csv()

In [3]:
pd.set_option('display.max_rows', 300)

In [4]:
df= pd.read_csv('Data_New/comments_likes_data_7.csv', encoding='utf-8')

In [5]:
df.columns

Index(['comment_post_link', 'comment_content', 'comment_likes_counts',
       'like_names', 'like_headlines', 'like_profile_links',
       'comment_reply_counts', 'comments_replies_content',
       'comments_replies_names', 'comments_replies_headlines',
       'comments_replies_links'],
      dtype='object')

In [6]:
df

,comment_post_link,comment_content,comment_likes_counts,like_names,like_headlines,like_profile_links,comment_reply_counts,comments_replies_content,comments_replies_names,comments_replies_headlines,comments_replies_links
0,https://www.linkedin.com/feed/update/urn%3Ali%...,The sadder thing is the most reliable informat...,19,['\n Shambhavi Aggarwal\n ...,"['Machine learning enthusiast', 'Data Scientis...",['https://www.linkedin.com/in/shambhavi-aggarw...,2,['\n\nPrudhvi Potuganti you are right as they ...,"['Abhirup Goswami', 'Nikhil Kumar']",['\n Student at IIT BHU Varanasi\n ...,['https://www.linkedin.com/in/abhirup-goswami-...
1,https://www.linkedin.com/feed/update/urn%3Ali%...,I really like your posts on edutech sir ! Woul...,3,['\n Nalini Singh\n \n ...,['Big Data Enthusiast • ETL Developer • Consul...,['https://www.linkedin.com/in/nalini-singh-8ba...,0,['NA'],['NA'],['NA'],['NA']
2,https://www.linkedin.com/feed/update/urn%3Ali%...,Good to see. !\n\n,3,['\n Saish Urumkar\n \n ...,['5G NR | BSC-RNC | Cloud | IOT | ML | Securit...,['https://www.linkedin.com/in/saish-mlnetwengg...,0,['NA'],['NA'],['NA'],['NA']
3,https://www.linkedin.com/feed/update/urn%3Ali%...,And you have to be a bayesian to be naive !! T...,18,['\n Sandhaya Kumari\n \n ...,"['Intern at Deep Cognition', 'Business Strateg...","['https://www.linkedin.com/in/sandhaya4u/', 'h...",1,['\n\n🙂🙂..The frequentists who think they know...,['Ritesh Bhagwat'],['\n Data Scientist | Applied Mathemati...,['https://www.linkedin.com/in/riteshb15/']
4,https://www.linkedin.com/feed/update/urn%3Ali%...,"Before you ask, give !! Summary of your post !...",11,['\n Srivatsan Srinivasan\n ...,"['Chief Data Scientist | Data (Big, Huge, Smal...",['https://www.linkedin.com/in/srivatsan-sriniv...,0,['NA'],['NA'],['NA'],['NA']
5,https://www.linkedin.com/feed/update/urn%3Ali%...,95% of 50 is almost as good 5% of 1000 FOCUS o...,22,['\n Mehul Purohit\n \n ...,['Software Developer(AI) at Office Beacon LLC'...,['https://www.linkedin.com/in/mehul-purohit-1b...,3,"[""\n\nThat's a great way to put it and a persp...","['Lakshmi Padmanaban', 'Prudhvi Potuganti', 'L...",['\n Freelance Copywriter | Content Wri...,['https://www.linkedin.com/in/lakshmipadmanaba...
6,https://www.linkedin.com/feed/update/urn%3Ali%...,Lakshmi Padmanaban ha ha. Have seen both and a...,2,['\n Lakshmi Padmanaban\n ...,['Freelance Copywriter | Content Writer | Copy...,['https://www.linkedin.com/in/lakshmipadmanaba...,0,['NA'],['NA'],['NA'],['NA']
7,https://www.linkedin.com/feed/update/urn%3Ali%...,Omg.. pls. Not even 0.0001%\n\n,0,NaN,NaN,NaN,0,['NA'],['NA'],['NA'],['NA']
8,https://www.linkedin.com/feed/update/urn%3Ali%...,srinivasan saripalli yes.\n\n,0,NaN,NaN,NaN,0,['NA'],['NA'],['NA'],['NA']
9,https://www.linkedin.com/feed/update/urn%3Ali%...,Srivatsan Srinivasan Thanks. Means a lot\n\n,0,NaN,NaN,NaN,0,['NA'],['NA'],['NA'],['NA']
10,https://www.linkedin.com/feed/update/urn%3Ali%...,"Ha ha. I am taking this as a compliment. Yes, ...",1,['\n Vanshika Agrawal\n \n...,['Project Manager at upGrad.com'],['https://www.linkedin.com/in/vanshika-agrawal...,0,['NA'],['NA'],['NA'],['NA']
11,https://www.linkedin.com/feed/update/urn%3Ali%...,3.41 has a good view of road which shows a big...,2,['\n Bharath Gujjula\n \n ...,['A Machine Learning (ML) and Deep Leaning (DL...,['https://www.linkedin.com/in/bharath-gujjula/...,0,['NA'],['NA'],['NA'],['NA']
12,https://www.linkedin.com/feed/update/urn%3Ali%...,Thanks a lot Manvi Madan\n\n,1,['\n Manvi Madan\n \n 2...,['Business Intelligence & Insights Analyst at ...,['https://www.linkedin.com/in/manvimadan/'],0,['NA'],['NA'],['NA'],['NA']
13,https://www.linkedin.com/feed/update/urn%3Ali%...,Sent you PM\n\n,0,NaN,NaN,NaN,0,['NA'],['NA'],['NA'],['NA']
14,https://www.linkedin.com/feed/update/urn%3Ali%...,Thanks. Very true.\n\n,1,['\n Avi Garg\n \n 2nd ...,['Senior Big Data Engineer|NIT Hamirpur'],['https://www.linkedin.com/in/avi-garg-a2754b6...,0,['NA'],['NA'],['NA'],['NA']
15,https://www.linkedin.com/feed/update/urn%3Ali%...,Very true !!\n\n,0,NaN,NaN,NaN,0,['NA'],['NA'],['NA'],['NA']
16,https://www.linkedin.com/feed/update/urn%3Ali%...,https://www.thehindu.com/sci-tech/technology/o...,2,['\n Dilpreet Singh\n \n ...,"['Co-founder Aqua18', 'Data Scientist at IKS H...",['https://www.linkedin.com/in/dilpreet-singh-c...,0,['NA'],['NA'],['NA'],['NA']
17,https://www.linkedin.com/feed/update/urn%3Ali%...,🤣🤣\n\n,0,NaN,NaN,NaN,0,['NA'],['NA'],['NA'],['NA']
18,https://www.linkedin.com/feed/update/urn%3Ali%...,Very true.. !! Been struggling to keep focusse...,1,['\n Reddeiah Pidugu\n \n ...,['Data Engineer (Python/Java/Scala)'],['https://www.linkedin.com/in/reddypidugu/'],0,['NA'],['NA'],['NA'],['NA']
19,https://www.linkedin.com/feed/update/urn%3Ali%...,When Sachin Tripathi asked me to define whats ...,25,['\n Amanjeet Sahu\n \n ...,['Data Science Intern at SupervisedLearning.co...,"['https://www.linkedin.com/in/amanjeetsahu/', ...",2,"['\n\nYeah Prudhvi\n\n', '\n\nAgree Ankit\n\n']","['Ankit Rathi', 'Rishi Narang']",['\n Lead Architect - Data & AI | Autho...,"['https://www.linkedin.com/in/ankitrathi/', 'h..."

In [46]:
def return_likes(df):
    df.like_names= df.like_names.fillna("['NaN']")
    df.like_headlines= df.like_headlines.fillna("['NaN']")
    df.like_profile_links= df.like_profile_links.fillna("['NaN']")
    df['like_names']= df['like_names'].apply(literal_eval)
    df['like_headlines']= df['like_headlines'].apply(literal_eval)
    df['like_profile_links']= df['like_profile_links'].apply(literal_eval)
    raw_names= list(itertools.chain.from_iterable(df.like_names.tolist()))
    names= list()
    for name in raw_names:
        try:
            names.append(re.match('^.*(?=(\n|•))', name).group(0))
        except Exception:
            names.append(name)
    headlines= list(itertools.chain.from_iterable(df.like_headlines.tolist()))
    links= list(itertools.chain.from_iterable(df.like_profile_links.tolist()))
    likes_df= pd.DataFrame({'name': names, 'headlines': headlines, 'links': links})
    likes_df= likes_df[likes_df.name != 'NaN']
    return likes_df

In [53]:
df.columns

Index(['comment_post_link', 'comment_content', 'comment_likes_counts',
       'like_names', 'like_headlines', 'like_profile_links',
       'comment_reply_counts', 'comments_replies_content',
       'comments_replies_names', 'comments_replies_headlines',
       'comments_replies_links'],
      dtype='object')

In [56]:
df.comments_replies_names= df.comments_replies_names.apply(literal_eval)

In [ ]:
df.comments_replies_names

In [47]:
def replies_df(df):
    df.comments_replies_content= df.comments_replies_content.fillna("['NaN']")
    df.comments_replies_names= df.comments_replies_names.fillna("['NaN']")
    df.comments_replies_headlines= df.comments_replies_headlines.fillna("['NaN']")
    df.comments_replies_links= df.comments_replies_links.fillna("['NaN']")
    df['comments_replies_content']= df['comments_replies_content'].apply(literal_eval)
    df['comments_replies_names']= df['comments_replies_names'].apply(literal_eval)
    df['comments_replies_headlines']= df['comments_replies_headlines'].apply(literal_eval)
    df['comments_replies_links']= df['comments_replies_links'].apply(literal_eval)
    raw_names= list(itertools.chain.from_iterable(df.comments_replies_names.tolist()))
    names= list()
    for name in raw_names:
        try:
            names.append(re.match('^.*(?=(\n|•))', name).group(0))
        except Exception:
            names.append(name)
    headlines= list(itertools.chain.from_iterable(df.comments_replies_headlines.tolist()))
    links= list(itertools.chain.from_iterable(df.like_profile_links.tolist()))
    likes_df= pd.DataFrame({'name': names, 'headlines': headlines, 'links': links})
    likes_df= likes_df[likes_df.name != 'NaN']
    return likes_df

In [48]:
likes_df= return_likes(df)

In [52]:
replies_df= replies_df(df)

ValueError: malformed node or string: ['Preksha Kaparwan • Following']

In [50]:
likes_df.name.value_counts()

Abhirup Goswami                          2
Preksha Kaparwan                         2
Haripriya Salapaka                       2
Krishnan Santhosh Kumar                  2
Swapnil Chavan                           2
saigayatri vadali                        1
Arpan Shrivastava                        1
Apurwa Raikwar                           1
Yeshavanth Nanjundappa                   1
Dalee Davis                              1
Olawale Ibrahim                          1
Sidharth SK                              1
Ankit Rathi                              1
karthikeyan MG                           1
Rahul Jain                               1
Dayanithi Selvaraji                      1
Nagesh Kalluri                           1
Shubham Tripathi                         1
Kuldeep Singh                            1
Mehul Harsora                            1
Santosh Yadav, PhD (EE), IIT Guwahati    1
Saurabh Goel,AINS                        1
Deepak Chaudhary                         1
Ramraj Sekar                             1
Srivatsan Srinivasan                     1
Ambika Iragappa                          1
Chandan Yadav                            1
Apoorva CR                               1
Rishabh Jain                             1
Sreekumar Radhakrishnapillai, Ph.D       1
Gautam .                                 1
sairam uppugundla                        1
Aryabhatta (.                            1
Prudhvi Potuganti                        1
Jatin Dinesh                             1
Nagesh GP                                1
Sourav Maharana                          1
Bhavesh Wadhwani                         1
ASHOK KUMAR CHITTURI                     1
Sunkoju Suryateja                        1
Ritesh Bhagwat                           1
Roshan T John ( Data Scientist )         1
Mousam Singh                             1
Suresh Pathange                          1
Deep Chatterjee                          1
Sailesh Satpathy                         1
Shivendra Agarwal                        1
Shibu Nair                               1
Amrita Angappa                           1
Chakravarthi Palvadi                     1
Dr Aniruddha Malpani                     1
Mayank Gupta                             1
Sandeep Dubey                            1
Taj Tabir Azad Khan                      1
Deeparaj Annamalai                       1
Sridhar Joga                             1
Aritra Das                               1
Swetha Kondapalli                        1
Ankush Rana                              1
Name: name, dtype: int64

In [47]:
import pandas as pd
dump_df= pd.read_csv("../data_dump/Comments.csv")

In [48]:
dump_df.columns

Index(['Date', 'Link', 'Message'], dtype='object')

In [49]:
dump_df.Link.isna().sum()

117

In [50]:
pd.set_option('display.max_rows', 800)

In [51]:
i=0
while(i < dump_df.shape[0]):
    if pd.isnull(dump_df.Link[i]):
        dump_df.Message[i-1]= str(dump_df.Message[i-1]) + str(dump_df.Date[i])
        dump_df.Message[i-1]= dump_df.Message[i-1].replace('nan', '')
        dump_df.drop(dump_df.index[i], inplace= True)
        dump_df.reset_index(drop= True, inplace= True)
        i= i-1
    i = i + 1

In [56]:
dump_df.Message[0]

'Actually, I wanted a girl/women entrepreneur to write the first line. So that I could ask them the opposite version - like what would be hobby answer from a woman entrepreneur. \r\n\r\nNow I should edit my post to tag women entrepreneurs whom I adore to write an opposite version !!. Bdw, I have a ton of women entrepreneurs in my network and I deeply value their work. FYI, one of my non profit - The Positive India has a woman Co Founder. \r\n\r\nPreksha Kaparwan Any help in opposite version ??\r\n\r\nOthers who are replying, request not to extrapolate too far'

In [60]:
len(dump_df.Link.unique())

457